version: '3.8'
    
networks:
  rentweb:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16
         gateway: 172.21.0.1


services:
    db:
        container_name: db
        image: sqlimage
        restart: unless-stopped
        ports:
            - 1433:1433
        networks:
            rentweb:
                ipv4_address: 172.21.0.4
        environment:
            - ACCEPT_EULA=1
            - MSSQL_PID=Developer
            - MSSQL_USER=SA
            - MSSQL_SA_PASSWORD=Root12345_
            - MSSQL_DATA_DIR=/var/opt/mssql/data
            - MSSQL_LOG_DIR=/var/opt/mssql/log
            - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
            - MSSQL_RPC_PORT=135

    vault:
        container_name: vault
        image: vaultfinal
        restart: unless-stopped
        ports:
            - 8200:8200
        networks:
            rentweb:
                ipv4_address: 172.21.0.5
        environment:
            - VAULT_ADDR=http://0.0.0.0:8200
            - VAULT_DEV_ROOT_TOKEN_ID="hvs.Klr7WSS9QJFx5StuD5fmd0Qf"
        cap_add:
            - IPC_LOCK

    keycloakcp:
        container_name: keycloak
        image: keycloakfinalv3
        ports:
          - 8080:8080
        environment:
            -KEYCLOAK_ADMIN: admin
            -KEYCLOAK_ADMIN_PASSWORD: admin
            -PROXY_ADDRESS_FORWARDING: true
        networks:
            rentweb:
                ipv4_address: 172.21.0.3
        volumes:
            - ./realm.json:/tmp/realm.json

        restart: unless-stopped

    rentapp:
        container_name: rentapp
        image: rentapp.war
        ports:
            - 9001:8080
            - 8443:8443
        expose:
            - 8443:8443
        networks:
            rentweb:
                ipv4_address: 172.21.0.2
        restart: unless-stopped
